version: "3.1"
services:
  hackyeah_db:
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    image: mariadb:10.2
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 127.0.0.45:3306:3306
    container_name: hackyeah_db
  #      command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
  hackyeah_php:
    environment:
      - XDEBUG_CONFIG=remote_host=${REMOTE_HOST-172.24.0.1} idekey=PHPSTORM
      - PHP_IDE_CONFIG=serverName=hackyeah.loc
    image: dzordz/xdebug-nginx-php
    container_name: hackyeah_php
    working_dir: /var/www/app/
    volumes:
      - .:/var/www/app
      - ./docker/vhost.conf:/etc/nginx/sites-available/default.conf
    ports:
      - 127.0.0.45:80:80
    expose:
      - "9000"
    links:
      - hackyeah_db
